"""Chapter 7: the design insights the model produced."""
from __future__ import annotations

from model import Chapter, Section, T

CHAPTER = Chapter(
    id="ch7", title=T("7 设计洞察", "7 Design insights"),
    sections=(
        Section(
            id="insights",
            title=T("7.1 模型换来的电路结论", "7.1 Circuit conclusions the model paid for"),
            body=(
                T("<b>① 4096-QAM 必须配低相噪综合器。</b>IPN ≈ −38 dBc 的 LO "
                  "单独就吃掉整个 −38 dB EVM 预算——CPE 去除救不了子载波间"
                  "相噪;需要 −43 dBc 量级。模型默认剖面按 PLL 组的抖动"
                  "指标锚定:120 fs rms(10 kHz–100 MHz 积分,6 GHz 载频,"
                  "IPN −46.9 dBc,0.26° rms)。积分下限取 10 kHz 是 CPE "
                  "给的松绑——更近端的 frac-N 噪声被逐符号公共相位去除"
                  "赦免。这是给 PLL 组的硬指标,不是仿真参数偏好。",
                  "<b>① 4096-QAM demands a low-phase-noise synthesizer.</b> "
                  "An LO at IPN ≈ −38 dBc alone consumes the entire −38 dB "
                  "EVM budget — CPE removal does not rescue "
                  "inter-subcarrier phase noise; a −43 dBc class is "
                  "required. The default profile is anchored to the PLL "
                  "team's jitter target: 120 fs rms (integrated "
                  "10 kHz–100 MHz at the 6 GHz carrier; IPN −46.9 dBc, "
                  "0.26° rms). The 10 kHz lower integration bound is "
                  "CPE's gift — closer-in fractional-N noise is absolved "
                  "by per-symbol common-phase removal. A hard requirement "
                  "for the PLL team, not a simulation preference."),
                T("<b>② 320 MHz 模式的 TX 基带 LPF 必须比信道宽"
                  "(≥1.3×BW/2)。</b>DPD 预失真频谱比信号宽;corner 贴着"
                  "信道边沿会把校正剥掉,PA 残余 EVM 卡在 −39 dB 附近,"
                  "怎么加迭代都无用。滤波器规格要为 DPD 留带宽。",
                  "<b>② The 320 MHz-mode TX baseband LPF must be wider "
                  "than the channel (≥1.3×BW/2).</b> The predistorted "
                  "spectrum is wider than the signal; a corner hugging the "
                  "channel edge strips the correction and pins residual "
                  "PA EVM near −39 dB no matter how many iterations run. "
                  "Spec the filter for DPD bandwidth."),
                T("<b>③ IIP2 校准必须排在 LO 泄漏校准之后。</b>PA 三阶积 "
                  "$f_2\\times leak\\times f_1^*$ 正落在 IM2 测量 bin,"
                  "未校泄漏埋掉 null ~35 dB。这是校准<em>顺序</em>由电路"
                  "机理决定的最典型例子。",
                  "<b>③ The IIP2 cal must follow the LO-leak cal.</b> The "
                  "PA product $f_2\\times leak\\times f_1^*$ lands exactly "
                  "on the IM2 measurement bin; an uncalibrated leak buries "
                  "the null by ~35 dB. The clearest case of calibration "
                  "<em>order</em> being dictated by circuit mechanism."),
                T("<b>④ 跟踪环的遗忘因子按块不按样本。</b>RLS 每块更新一次时,"
                  "forget=0.995 意味着几乎永不遗忘,PA 漂移后残留 20 dB 滞后;"
                  "块级 forget=0.4 才是同一物理时间常数的正确换算。",
                  "<b>④ Tracking-loop forgetting factors are per block, "
                  "not per sample.</b> With one RLS update per block, "
                  "forget=0.995 means almost never forgetting — 20 dB of "
                  "lag after PA drift; block-level forget=0.4 is the same "
                  "physical time constant correctly rescaled."),
                T("<b>⑤ 窄带模式:校准激励随带宽缩放,corner 比例保持"
                  "统一。</b>23 MHz 探测音在 20 MHz 信道里是带外音——IIP2 "
                  "trim 在噪声上乱走、AGC 扫描读不到 SNR,这是窄带校准失败"
                  "的真正(也是唯一的)功能性原因,激励频率必须随带宽缩放。"
                  "corner 比例则全带宽统一 1.3×(TX)/1.12×(RX):无伪影"
                  "仪表实测 20 MHz 单 LPF 地板 −55/−50 dB,比整链实际到达"
                  "的 ~−42 dB 低 12 dB 以上。曾短暂采用的窄带 3× 策略已"
                  "撤销——它只买到没人消费的余量(TX EVM +1.5 dB、环回观测"
                  "底板 +11 dB),代价是邻道模拟抑制从 ~25 dB 塌到 ~0 dB、"
                  "blocker 全压到 ADC 动态范围。EVM 指标不给 blocker 定价,"
                  "corner 规格必须给。此条由 20 MHz GUI 运行的异常直接换来。",
                  "<b>⑤ Narrow modes: scale calibration probes with "
                  "bandwidth; keep the corner ratios uniform.</b> A "
                  "23 MHz probe tone is out-of-channel at 20 MHz — the "
                  "IIP2 trim walks on noise and the AGC sweep reads no "
                  "SNR at all; that is the real (and only) functional "
                  "failure of narrow-mode calibration, so probe "
                  "frequencies must scale with bandwidth. The corner "
                  "ratios stay uniform at every bandwidth — 1.3× (TX) / "
                  "1.12× (RX): the artifact-free 20 MHz single-LPF "
                  "floors are −55/−50 dB, 12+ dB below the ~−42 dB the "
                  "calibrated chain actually reaches. A briefly-adopted "
                  "3× narrow-mode policy was reverted: it bought only "
                  "unconsumed margin (+1.5 dB TX EVM, +11 dB loopback-"
                  "observation floor) while collapsing analog adjacent-"
                  "channel rejection from ~25 dB to ~0 dB, dumping the "
                  "blocker onto ADC dynamic range. EVM does not price "
                  "blockers; the corner spec must. Paid for directly by "
                  "an anomalous 20 MHz GUI run."),
                T("<b>⑥ 先校准测量仪器,再给电路定规格。</b>最初诊断出的"
                  "\"1.3× corner 在 20 MHz 把 EVM 钉死在 −33 dB\"是测量"
                  "伪影:测试接收机模型的时延补偿用循环 FFT 移位整体前移"
                  "捕获,把 warm-up 样本卷进最后一个符号的 FFT 窗。误差"
                  "正比于滤波器群时延(所以跟着 corner 变!)、反比于 FFT "
                  "长度(所以 320 MHz 看不见、20 MHz 最重),完美伪装成"
                  "物理 ISI 地板;换一个符号数,数字就漂移——这正是暴露"
                  "它的线索。修复后还剩第二层:时延补偿把最后一个符号的 "
                  "FFT 窗推出 burst 末尾几个采样,截断的 ramp-down 让延续"
                  "内容失真,在深地板上仍值 >8 dB——现在多发一个 padding "
                  "符号、只对内部符号打分(实验室标准做法)。全部修完后"
                  "真实地板在 1.3× 即有 −55 dB,基于伪影数据定下的窄带 "
                  "3× corner 策略随之撤销(见⑤)。任何随测量配置漂移的"
                  "\"物理结论\"都要先怀疑测量本身。",
                  "<b>⑥ Calibrate the measuring instrument before "
                  "spec'ing the circuit.</b> The originally diagnosed "
                  "\"−33 dB EVM floor at a 1.3× corner\" was a "
                  "measurement artifact: the test-receiver model's delay "
                  "compensation circularly advanced the whole capture, "
                  "wrapping warm-up samples into the last symbol's FFT "
                  "window. The error scales with filter group delay (so "
                  "it tracked the corner!) and inversely with FFT size "
                  "(so 320 MHz never saw it and 20 MHz was hit hardest) "
                  "— a perfect impostor of a physical ISI floor. Its "
                  "numbers drifted with the symbol count, which is the "
                  "clue that exposed it. A second layer remained after "
                  "the fix: delay compensation pushes the final symbol's "
                  "FFT window a few samples past the burst end, where "
                  "the truncated ramp-down misrepresents the "
                  "continuation — still worth >8 dB on deep floors; the "
                  "EVM meter now transmits one padding symbol and "
                  "scores interior symbols only (lab practice). With "
                  "both fixed, the true floor at 1.3× is already "
                  "−55 dB, and the narrow-mode 3× corner policy that "
                  "had been founded on the artifact data was reverted "
                  "(see ⑤). Any \"physical\" conclusion that drifts "
                  "with the measurement configuration indicts the "
                  "measurement first."),
                T("<b>⑥ 的后续:同样的怀疑用在 20 MHz 底板上,这次仪表是"
                  "干净的。</b>11ac/n 编号(64-FFT)下隔离底板读 −46.4 dB,"
                  "比 11ax/be(256-FFT)的 −48.4 差 1.9 dB,正好落在⑥描述的"
                  "\"反比于 FFT 长度\"的嫌疑区。判据是宽 corner 极限:无损伤"
                  "链路把信道滤波器整个旁路后,再没有任何东西能损伤信号,"
                  "正确的仪表必须读出数值零——实测 <b>−309.8 dB</b>。"
                  "底板随 corner 从 −46.4 单调降到 −88 dB(40 dB 跨度),"
                  "一路跟着滤波器走、随滤波器消失而归零,所以它<b>全部是"
                  "真实 ISI</b>;64-FFT 差的那 1.9 dB 也是物理的——子载波宽 "
                  "312.5 kHz 而不是 78 kHz,逐音均衡\"响应在子载波内是常数\""
                  "的假设更差。顺带澄清一个容易误读的现象:窄带下那条 "
                  "\"PN+ADC+底板\"合成曲线确实抬高了,但<b>相噪本身没变</b>"
                  "——8 个实现平均,PN 单独在 20–320 MHz 上都是 −45.2 ±0.3 dB"
                  "(解析积分同样给出各带宽一致的 −44.5 dBc:剖面能量全在"
                  "近端,把上限从 10 MHz 拉到 160 MHz 几乎不增加什么)。"
                  "抬高的是底板,而那条曲线是个和。",
                  "<b>⑥, continued: the same suspicion applied to the "
                  "20 MHz floor — and this time the instrument was "
                  "clean.</b> Under 11ac/n numerology (64-point FFT) the "
                  "isolation floor reads −46.4 dB against −48.4 for "
                  "11ax/be (256-point) — 1.9 dB worse, landing squarely "
                  "in the \"inversely proportional to FFT length\" "
                  "suspect zone ⑥ describes. The discriminator is the "
                  "wide-corner limit: bypass the channel filter on an "
                  "impairment-free chain and nothing is left to degrade "
                  "the signal, so a correct harness must read numerical "
                  "zero. It reads <b>−309.8 dB</b>. The floor falls "
                  "monotonically with the corner from −46.4 to −88 dB — "
                  "40 dB of range — tracking the filter the whole way and "
                  "vanishing with it, so it is <b>all real ISI</b>. The "
                  "1.9 dB the 64-point FFT gives away is physical too: "
                  "subcarriers are 312.5 kHz wide instead of 78 kHz, so "
                  "per-tone equalization's \"response is constant across "
                  "a subcarrier\" assumption holds less well. One "
                  "easily-misread symptom while we are here: the combined "
                  "\"PN + ADC + floor\" curve does rise in narrow modes, "
                  "but <b>phase noise itself does not move</b> — averaged "
                  "over 8 realizations it is −45.2 ±0.3 dB from 20 to "
                  "320 MHz (the analytic integral agrees, −44.5 dBc at "
                  "every bandwidth: the profile's energy is all close-in, "
                  "so raising the upper limit from 10 to 160 MHz adds "
                  "almost nothing). What rose is the floor, and that "
                  "curve is a sum."),
                T("<b>⑦ AGC 把 VGA 输出钉死,所以基带的输出天花板是唯一"
                  "躲不掉的损伤。</b>把模拟基带显式建模(按电路口径:输入"
                  "参考噪声电压密度 + 输出摆幅,而不是 NF/IIP3)之后,输入"
                  "参考 IIP3 随 VGA 增益 1 dB/dB 塌陷;而 AGC 把 VGA "
                  "<b>输出</b>伺服在固定电平,于是输出参考压缩的 EVM 代价"
                  "<b>与天线功率无关</b>——实测 −40 dBm 与 −20 dBm 处都是 "
                  "+2.55 dB。它躲不开任何增益档,唯一的缓解手段是加大 ADC "
                  "backoff,于是 <code>adc_backoff_db</code> 从自由参数变成"
                  "有价参数:1.0 Vpp 下最优 backoff 从 ~10 dB 推到 ≥18 dB。"
                  "顺带纠正一条直觉:基带噪声在 VGA <b>之前</b>,不可能带来"
                  "\"NF 随 VGA 变\"——那个效应来自 ADC,模型里本来就有。",
                  "<b>⑦ The AGC pins the VGA output, so the baseband's "
                  "output ceiling is the one impairment nothing "
                  "escapes.</b> Model the analog baseband explicitly — the "
                  "way a circuit is specified, by input-referred noise "
                  "voltage density and output swing rather than NF/IIP3 — "
                  "and the input-referred IIP3 collapses 1 dB per dB of "
                  "VGA gain. Because the AGC servos the VGA <b>output</b> "
                  "to a fixed level, the EVM cost of an output-referred "
                  "compression is <b>independent of antenna power</b>: "
                  "+2.55 dB at −40 dBm and at −20 dBm alike. No gain "
                  "state escapes it and the only relief is more ADC "
                  "backoff, which turns <code>adc_backoff_db</code> from a "
                  "free parameter into a priced one — at 1.0 Vpp the "
                  "optimum moves from ~10 dB to ≥18 dB. It also corrects "
                  "an intuition: baseband noise sits <b>before</b> the "
                  "VGA and cannot make the noise figure depend on VGA "
                  "gain. That effect comes from the ADC, and the model "
                  "always had it."),
                T("<b>⑧ \"关掉一个源再相减\"对确定性损伤是错的口径。</b>"
                  "分解 EVM 贡献时,全量读数减去关掉某源的读数,得到的不是"
                  "该源的功率,而是 <code>|e_源|² + 2Re⟨e_源, e_其余⟩</code>。"
                  "交叉项对随机源(热噪声、量化)因独立而消失,对确定性源"
                  "(IM3、基带天花板、ISI 同源于信号)一点都不小:实测基带"
                  "天花板在 1.0 Vpp 处交叉项占 <b>48%</b>(0.5 Vpp 时 19%,"
                  "2.0 Vpp 时 76%),把它对 OIP3 的斜率从解析值 −2.00 压到 "
                  "−1.49 dB/dB——照着这条曲线定规格会系统性<b>低估</b>加"
                  "摆幅/加 backoff 的收益。判据很硬:孤立立方原语(不接链路)"
                  "给出精确的 −2.00/+2.01,两项拟合 <code>a/P₃²+b/P₃</code> "
                  "的残差 0.14 dB(单项模型 3.3 dB),拟合出的纯失真项与孤立"
                  "实测差 0.1 dB。改用<b>隔离法</b>(只开该损伤直接读数)"
                  "即可消除;代价是能隔离的只有无校正的源——IQ/DC/LPF 的"
                  "校正是减法型的,只关注入不关校正会注入等量反向误差。"
                  "隔离曲线<b>不满足功率相加</b>,别当预算表逐项加。",
                  "<b>⑧ \"Switch one source off and subtract\" is the "
                  "wrong measure for deterministic impairments.</b> "
                  "Subtracting a switch-off reading from the full one "
                  "does not give that source's power; it gives "
                  "<code>|e_source|² + 2Re⟨e_source, e_rest⟩</code>. The "
                  "cross term vanishes for random sources (thermal noise, "
                  "quantization) but not for deterministic ones — IM3, "
                  "the baseband ceiling and ISI all derive from the same "
                  "signal. Measured on the ceiling: the cross term is "
                  "<b>48%</b> of the extracted contribution at 1.0 Vpp "
                  "(19% at 0.5, 76% at 2.0) and flattens its OIP3 slope "
                  "from the analytic −2.00 to −1.49 dB/dB — so spec'ing "
                  "from that curve <b>understates</b> what more swing or "
                  "more backoff buys. The evidence is hard: the isolated "
                  "cubic primitive, no chain attached, gives exactly "
                  "−2.00/+2.01; fitting <code>a/P₃² + b/P₃</code> leaves "
                  "0.14 dB rms against 3.3 dB for either term alone, and "
                  "the fitted pure-distortion term lands 0.1 dB from the "
                  "isolated measurement. <b>Isolation</b> — read the chain "
                  "with only that source active — removes the bias; the "
                  "price is that only sources without a correction can be "
                  "isolated, since IQ/DC/LPF corrections are subtractive "
                  "and removing the injection while keeping the "
                  "correction injects an equal and opposite error. "
                  "Isolated curves are <b>not power-additive</b>; do not "
                  "add them up as a budget."),
                T("<b>⑨ AGC 切换门限是 320 MHz 锚定的,窄带下白丢约 1 dB。</b>"
                  "门限解自噪声-IM3 平衡点 <code>t_i = (2·IIP3_i + NF_(i+1) "
                  "+ (−174 + 10log10 BW))/3</code>,平衡点随噪声底板走——"
                  "也就是<b>带宽变化的 1/3</b>。出厂表在 320 MHz 上解一次、"
                  "一套寄存器值用在所有带宽,于是 20 MHz 下每档门限偏高 "
                  "<b>4.0 dB</b>,每一档都被留过了自己的平衡点:省下的是"
                  "用不着的热噪声余量,付出的是实实在在的 IM3。实测 "
                  "20 MHz/4096-QAM 强信号段,重解后平均 EVM 好 <b>1.16 dB</b>、"
                  "锯齿起伏从 2.8 dB 收到 <b>1.45 dB</b>、单点最大 "
                  "<b>3.17 dB</b>。结构干净得可以自证:两种配置<b>落在同一档"
                  "的点差值恰好 0.00 dB</b>,收益全部来自换档位置改变的点"
                  "(平均 1.87 dB),而收益最大的正是紧贴门限下方 IM3 达峰处"
                  "——重解把换档提前,那些点就不存在了。门限做成带宽相关要多"
                  "一套寄存器与固件逻辑,值不值由系统组定,模型只负责把价码"
                  "测出来(GUI 的 <code>agc_rebw</code> 开关)。",
                  "<b>⑨ The AGC hand-over thresholds are anchored at "
                  "320 MHz, and narrow modes give away about 1 dB for "
                  "it.</b> The thresholds solve the noise-vs-IM3 balance "
                  "point <code>t_i = (2·IIP3_i + NF_(i+1) + (−174 + "
                  "10log10 BW))/3</code>, and that point tracks the noise "
                  "floor — it moves by <b>a third of the bandwidth "
                  "change</b>. The shipped table solves it once at "
                  "320 MHz and uses one register set everywhere, so at "
                  "20 MHz every threshold sits <b>4.0 dB</b> high and each "
                  "state is held past its own balance point: it saves "
                  "thermal margin it no longer needs and pays IM3 it now "
                  "does. Measured at 20 MHz / 4096-QAM over the "
                  "strong-signal half, re-solving improves mean EVM by "
                  "<b>1.16 dB</b>, tightens the hand-over ripple from "
                  "2.8 dB to <b>1.45 dB</b>, and gains <b>3.17 dB</b> at "
                  "the best point. The structure is clean enough to check "
                  "itself: points where both configurations land in the "
                  "<b>same state differ by exactly 0.00 dB</b>, the whole "
                  "gain coming from points where the hand-over moved "
                  "(1.87 dB mean) — and the biggest gains are just below "
                  "a threshold, where that state's IM3 peaks, because "
                  "re-solving hands over before the signal gets there. "
                  "Whether a bandwidth-aware AGC is worth a register set "
                  "and firmware logic is the system team's call; the "
                  "model's job was to price it (the GUI's "
                  "<code>agc_rebw</code> switch)."),
            )),
    ))
