"""Fixed-point quantization sweep and hardware export of correction state.

The digital team consumes the calibration output as quantized coefficient
sets (widely-linear w1/w2 FIRs, DPD polynomial coefficients, DC words).
``quantization_sweep`` measures the EVM cost of each candidate bit width
with the coefficients quantized in place; ``select_min_bits`` picks the
smallest width within an allowed loss; exporters emit a C header and CSV.
"""
from __future__ import annotations

from pathlib import Path
from typing import Callable

import numpy as np

from .fixed_point import quantize_symmetric


def quantization_sweep(coeff_sets: dict[str, np.ndarray],
                       apply_and_measure: Callable[[dict], float],
                       bit_widths=(8, 10, 12, 14, 16)) -> dict:
    """EVM (or any metric, lower = better) vs coefficient bit width.

    ``apply_and_measure(quantized_sets) -> metric_db`` programs the given
    coefficient sets into the chains and returns the measured metric; the
    float reference is measured first.
    """
    ref = apply_and_measure(coeff_sets)
    rows = []
    for bits in bit_widths:
        q = {k: quantize_symmetric(np.asarray(v), bits)
             for k, v in coeff_sets.items()}
        rows.append({"bits": int(bits),
                     "metric_db": float(apply_and_measure(q)),})
    # restore float coefficients
    apply_and_measure(coeff_sets)
    return {"reference_db": float(ref), "rows": rows}


def select_min_bits(sweep: dict, max_loss_db: float = 0.5) -> int:
    for row in sweep["rows"]:
        if row["metric_db"] <= sweep["reference_db"] + max_loss_db:
            return row["bits"]
    return sweep["rows"][-1]["bits"]


def _fmt_c_complex(arr: np.ndarray) -> str:
    return ",\n    ".join(f"{{{v.real:+.10e}, {v.imag:+.10e}}}"
                          for v in np.asarray(arr, dtype=complex))


def export_c_header(coeff_sets: dict[str, np.ndarray], path: str | Path,
                    bits: int, guard: str = "WIFITRX_CAL_COEFFS_H") -> Path:
    """Emit quantized coefficients as C arrays of {re, im} pairs."""
    lines = [f"#ifndef {guard}", f"#define {guard}", "",
             "/* Generated by wifitrx deploy.export - calibration",
             f"   coefficients quantized to {bits}-bit symmetric format. */",
             "",
             "typedef struct { double re; double im; } wifitrx_cplx_t;", ""]
    for name, arr in coeff_sets.items():
        q = quantize_symmetric(np.asarray(arr, dtype=complex), bits)
        c_name = name.replace(".", "_").replace("-", "_")
        lines += [f"static const wifitrx_cplx_t {c_name}[{q.size}] = {{",
                  f"    {_fmt_c_complex(q)}", "};", ""]
    lines.append("#endif")
    p = Path(path)
    p.write_text("\n".join(lines))
    return p


def export_coeff_csv(coeff_sets: dict[str, np.ndarray], path: str | Path,
                     bits: int | None = None) -> Path:
    lines = ["set,index,re,im"]
    for name, arr in coeff_sets.items():
        a = np.asarray(arr, dtype=complex)
        if bits is not None:
            a = quantize_symmetric(a, bits)
        for i, v in enumerate(a):
            lines.append(f"{name},{i},{v.real:.12e},{v.imag:.12e}")
    p = Path(path)
    p.write_text("\n".join(lines))
    return p
